name: oncall
version: 0.0.1
description: Calendar tool designed for scheduling and managing on-call shifts
keywords:
  - calendar
  - schedule
  - shifts management
home: https://oncall.tools
sources:
  - https://github.com/linkedin/oncall
engine: gotpl
icon: https://raw.githubusercontent.com/linkedin/oncall/master/src/oncall/ui/static/images/favicon.png
appVersion: 0.0.14
